/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.Color;

/**
 *
 * @author honore
 */
public class Paraclinique extends javax.swing.JPanel {

    /**
     * Creates new form Paraclinique
     */
    public Paraclinique() {
        initComponents();
          jPanel7.setBackground(new Color(192, 192, 255));
          jPanel6.setBackground(new Color(192, 192, 255));
          jPanel4.setBackground(new Color(192, 192, 255));
           jPanel5.setBackground(new Color(192, 192, 255));
             jTable3.setBackground(new Color(192, 192, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pphysique = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        id = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jXSearchField1 = new org.jdesktop.swingx.JXSearchField();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        exit1 = new javax.swing.JLabel();
        exit2 = new javax.swing.JLabel();
        exit3 = new javax.swing.JLabel();
        exit4 = new javax.swing.JLabel();
        exit5 = new javax.swing.JLabel();
        exit6 = new javax.swing.JLabel();
        exit7 = new javax.swing.JLabel();
        exit8 = new javax.swing.JLabel();
        exit9 = new javax.swing.JLabel();
        sendTolabo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pphysique.setBackground(new java.awt.Color(255, 255, 255));
        pphysique.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 255)), "PARACLINIQUE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 10, 10));

        jLabel22.setForeground(new java.awt.Color(51, 0, 204));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("K. AUTRES  ");
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 20, 140, 40));

        jLabel23.setForeground(new java.awt.Color(51, 0, 204));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("A. HEMATOLOGIE");
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, 40));

        jLabel24.setForeground(new java.awt.Color(51, 0, 204));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("B. PARASITOLOGIE");
        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 130, 40));

        jLabel25.setForeground(new java.awt.Color(51, 0, 204));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("C.UROLOGIE");
        jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 130, 40));

        jLabel26.setForeground(new java.awt.Color(51, 0, 204));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("D. LCR ");
        jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 130, 40));

        jLabel27.setForeground(new java.awt.Color(51, 0, 204));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText(" E. SEROIMMUNOLOGIE");
        jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 140, 40));

        jLabel28.setForeground(new java.awt.Color(51, 0, 204));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("I.IONOGRAMME");
        jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, 140, 40));

        jLabel29.setForeground(new java.awt.Color(51, 0, 204));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("F.BIOCHIMIE");
        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 140, 40));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 204)), "Information sur Examen", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 14), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel5.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 430, 240));
        jPanel5.add(jXSearchField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 250, 30));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 490, 350));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 204)), "Etiquette", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 14), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("1");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("8");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 20, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("2");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 20, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("3");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 20, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("4");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 20, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("5");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 20, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("6");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 20, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 255));
        jLabel8.setText("7");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 20, -1));

        exit1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        exit1.setForeground(new java.awt.Color(255, 0, 51));
        exit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit1.setText("X");
        exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit1MouseClicked(evt);
            }
        });
        jPanel6.add(exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 40, 40));

        exit2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        exit2.setForeground(new java.awt.Color(255, 0, 51));
        exit2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit2.setText("X");
        exit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit2MouseClicked(evt);
            }
        });
        jPanel6.add(exit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 40, 30));

        exit3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        exit3.setForeground(new java.awt.Color(255, 0, 51));
        exit3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit3.setText("X");
        exit3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit3MouseClicked(evt);
            }
        });
        jPanel6.add(exit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 40, 30));

        exit4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        exit4.setForeground(new java.awt.Color(255, 0, 51));
        exit4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit4.setText("X");
        exit4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit4MouseClicked(evt);
            }
        });
        jPanel6.add(exit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 40, 30));

        exit5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        exit5.setForeground(new java.awt.Color(255, 0, 51));
        exit5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit5.setText("X");
        exit5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit5MouseClicked(evt);
            }
        });
        jPanel6.add(exit5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 40, 30));

        exit6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        exit6.setForeground(new java.awt.Color(255, 0, 51));
        exit6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit6.setText("X");
        exit6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit6MouseClicked(evt);
            }
        });
        jPanel6.add(exit6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 40, 30));

        exit7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        exit7.setForeground(new java.awt.Color(255, 0, 51));
        exit7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit7.setText("X");
        exit7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit7MouseClicked(evt);
            }
        });
        jPanel6.add(exit7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 40, 30));

        exit8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        exit8.setForeground(new java.awt.Color(255, 0, 51));
        exit8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit8.setText("X");
        exit8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit8MouseClicked(evt);
            }
        });
        jPanel6.add(exit8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 40, 30));

        exit9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        exit9.setForeground(new java.awt.Color(255, 0, 51));
        exit9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit9.setText("X");
        exit9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit9MouseClicked(evt);
            }
        });
        jPanel6.add(exit9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 40, 30));

        sendTolabo.setBackground(new java.awt.Color(255, 255, 255));
        sendTolabo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        sendTolabo.setForeground(new java.awt.Color(0, 0, 255));
        sendTolabo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sendTolabo.setText("Envoyer au labo");
        sendTolabo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 255)));
        sendTolabo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendTolaboMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sendTolaboMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sendTolaboMouseExited(evt);
            }
        });
        jPanel6.add(sendTolabo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 190, 40));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Envoyer à l'Imagerie");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 255)));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 200, 40));

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 255));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Ajouter un examen");
        jLabel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 255)));
        jLabel36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel36MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel36MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel36MouseExited(evt);
            }
        });
        jPanel6.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 180, 40));
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 460, 30));
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 460, 30));
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 460, 30));
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 460, 30));
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 460, 30));
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 460, 30));
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 460, 30));
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 460, 30));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 620, 350));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 204)), "Information generale", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 14), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel7.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1100, 90));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 1130, 120));

        pphysique.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1170, 540));

        add(pphysique, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1190, 840));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
//        sy.insertionPhysique(jLabel17, nom, postnom, prenom1, prenom2
//            , prenom3, numfiche1, numfiche2, adresse1,curatif2, curatif1,
//            echo1,cpn1,autre1,autre2,adresse2,curatif3,curatif4,echo2,cpn2,
//            autre3,"EXEC sp_identite ?,?,?,?,?,?,?,?,?,?,?,?");
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel29MouseClicked

    private void exit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MouseClicked
      //  exam1.setText("");
    }//GEN-LAST:event_exit1MouseClicked

    private void exit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_exit2MouseClicked

    private void exit3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_exit3MouseClicked

    private void exit4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_exit4MouseClicked

    private void exit5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_exit5MouseClicked

    private void exit6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_exit6MouseClicked

    private void exit7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_exit7MouseClicked

    private void exit8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_exit8MouseClicked

    private void exit9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_exit9MouseClicked

    private void sendTolaboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendTolaboMouseClicked
//        int id = t.ChargeridAgent(id_per, "identite", "id");
//        String id_pers = t.ChargerNomAgent(id_per, "identite", "NOM");
//        t.paraclinique(id_pers, AGENT, exam1, exam2, exam3, exam14, exam15, exam16, exam17, exam18, jTextArea3);
//        JOptionPane.showMessageDialog(null, "Examen Envoyer au laboratoire");
        // TODO add your handling code here:
    }//GEN-LAST:event_sendTolaboMouseClicked

    private void sendTolaboMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendTolaboMouseEntered
       // t.Changer(sendTolabo);        // TODO add your handling code here:
    }//GEN-LAST:event_sendTolaboMouseEntered

    private void sendTolaboMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendTolaboMouseExited
       // t.ExitChanger(sendTolabo);        // TODO add your handling code here:
    }//GEN-LAST:event_sendTolaboMouseExited

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
//        String id_pers = t.ChargerNomAgent(id_per, "identite", "NOM");
//        int id = t.ChargeridAgent(id_per, "identite", "id");
//        t.saveImagerieResult(id_per, AGENT, jTextArea4, exam1, exam2, exam3, exam14,
//            exam15, exam16, exam17, exam18);
//        JOptionPane.showMessageDialog(null, "Examen Envoyer a l'imagerie");        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        //t.Changer(jLabel11);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
       // t.ExitChanger(jLabel11);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseClicked
       // new AjouterMaladie().show();
    }//GEN-LAST:event_jLabel36MouseClicked

    private void jLabel36MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseEntered
       // t.Changer(jLabel36);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel36MouseEntered

    private void jLabel36MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseExited
        //t.ExitChanger(jLabel36);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel36MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exit1;
    private javax.swing.JLabel exit2;
    private javax.swing.JLabel exit3;
    private javax.swing.JLabel exit4;
    private javax.swing.JLabel exit5;
    private javax.swing.JLabel exit6;
    private javax.swing.JLabel exit7;
    private javax.swing.JLabel exit8;
    private javax.swing.JLabel exit9;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private org.jdesktop.swingx.JXSearchField jXSearchField1;
    public static javax.swing.JPanel pphysique;
    private javax.swing.JLabel sendTolabo;
    // End of variables declaration//GEN-END:variables
}
