/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Syncronisation.Syncroniser;
import java.awt.Color;

/**
 *
 * @author honore
 */
public class Physique extends javax.swing.JPanel {

    /**
     * Creates new form Physique
     */
     Syncroniser sy= new Syncroniser();
    public Physique() {
        initComponents();
    pphysique.setBackground(new Color(192, 192, 255));
       jPanel4.setBackground(new Color(192, 192, 255));
       jPanel2.setBackground(new Color(192, 192, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pphysique = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        adresse1 = new javax.swing.JTextField();
        prenom1 = new javax.swing.JTextField();
        numfiche1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        echo1 = new javax.swing.JTextField();
        cpn1 = new javax.swing.JTextField();
        curatif1 = new javax.swing.JTextField();
        autre1 = new javax.swing.JTextField();
        postnom = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        id = new javax.swing.JLabel();
        prenom2 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        prenom3 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        numfiche2 = new javax.swing.JTextField();
        autre2 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        curatif2 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        adresse2 = new javax.swing.JTextField();
        curatif3 = new javax.swing.JTextField();
        curatif4 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        echo2 = new javax.swing.JTextField();
        cpn2 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        autre3 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pphysique.setBackground(new java.awt.Color(255, 255, 255));
        pphysique.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 255)), "PHYSIQUE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(adresse1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 310, 30));
        jPanel4.add(prenom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 280, 30));
        jPanel4.add(numfiche1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 280, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Agent");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 40, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("Fc");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 60, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 153));
        jLabel19.setText("Mensuration_poids");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 110, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 153));
        jLabel20.setText("Ta");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 90, 30));

        jLabel21.setForeground(new java.awt.Color(51, 0, 204));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Modifié");
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 170, 40));

        jLabel22.setForeground(new java.awt.Color(51, 0, 204));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Enregistré");
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 170, 40));

        jLabel23.setForeground(new java.awt.Color(51, 0, 204));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Supprimé");
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 170, 40));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 153));
        jLabel24.setText("Sphere oral");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 90, 30));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 153));
        jLabel25.setText("Aires gangl");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 90, 30));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 153));
        jLabel26.setText("Paeu");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 90, 30));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 153));
        jLabel27.setText("Etat général");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 90, 30));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 153));
        jLabel28.setText("Pouls");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 90, 30));
        jPanel4.add(echo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 310, 30));
        jPanel4.add(cpn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 310, 30));
        jPanel4.add(curatif1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 310, 30));
        jPanel4.add(autre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 310, 30));
        jPanel4.add(postnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 280, 30));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 153));
        jLabel29.setText("Temp");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 60, 30));
        jPanel4.add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 280, 30));
        jPanel4.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 10, 10));
        jPanel4.add(prenom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 280, 30));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 153));
        jLabel30.setText("Fr");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 60, 30));
        jPanel4.add(prenom3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 280, 30));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 153));
        jLabel31.setText("Sa02");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 60, 30));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 153));
        jLabel32.setText("Taille");
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 110, 30));
        jPanel4.add(numfiche2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 280, 30));
        jPanel4.add(autre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 310, 30));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 153));
        jLabel33.setText("Thorax");
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 90, 30));
        jPanel4.add(curatif2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 310, 30));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 153));
        jLabel34.setText("Abdomen");
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 70, 30));

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 153));
        jLabel35.setText("Organe Gen");
        jPanel4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 60, 70, 30));
        jPanel4.add(adresse2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, 250, 30));
        jPanel4.add(curatif3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 60, 250, 30));
        jPanel4.add(curatif4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 90, 250, 30));

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 153));
        jLabel36.setText("Appareil loco");
        jPanel4.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, 90, 30));

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 153));
        jLabel37.setText("Examen neuro");
        jPanel4.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 120, 80, 30));
        jPanel4.add(echo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 120, 250, 30));
        jPanel4.add(cpn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 150, 250, 30));

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 153));
        jLabel38.setText("Resume_sydro");
        jPanel4.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 150, 90, 30));

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 153));
        jLabel39.setText("Hypothèse");
        jPanel4.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 180, 90, 30));
        jPanel4.add(autre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 180, 250, 30));

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 153));
        jLabel40.setText("Nom patient");
        jPanel4.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, 90, 30));

        jPanel4.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 210, 250, 30));

        jLabel17.setText("Code");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, -1));

        pphysique.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1150, 300));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 204)), "Information sur physique", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 14), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1130, 230));

        pphysique.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 1150, 260));

        add(pphysique, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 740));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        //sy.UpdatePatient(id, nom, postnom, sexe, date, adresse, curatif, mat, echo, cpn, prenom, autre, numfiche, "exec sp_modifieridentite ?,?,?,?,?,?,?,?,?,?,?,?,?");
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        sy.insertionPhysique(jLabel17, nom, postnom, prenom1, prenom2
        , prenom3, numfiche1, numfiche2, adresse1,curatif2, curatif1,
        echo1,cpn1,autre1,autre2,adresse2,curatif3,curatif4,echo2,cpn2,
        autre3,"EXEC sp_identite ?,?,?,?,?,?,?,?,?,?,?,?");
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        //sy.DeletePatient(id, "delete from IDENTITE WHERE ID=?");
        //sy.affichage(jTable1, "select * from IDENTITE");// TODO add your handling code here:
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        //sy.SelectionPatient(jTable1, nom, postnom, sexe, date, adresse, curatif, mat, echo, cpn, autre, numfiche, id, jLabel1, jLabel1, numfiche, prenom);
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adresse1;
    private javax.swing.JTextField adresse2;
    private javax.swing.JTextField autre1;
    private javax.swing.JTextField autre2;
    private javax.swing.JTextField autre3;
    private javax.swing.JTextField cpn1;
    private javax.swing.JTextField cpn2;
    private javax.swing.JTextField curatif1;
    private javax.swing.JTextField curatif2;
    private javax.swing.JTextField curatif3;
    private javax.swing.JTextField curatif4;
    private javax.swing.JTextField echo1;
    private javax.swing.JTextField echo2;
    private javax.swing.JLabel id;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField numfiche1;
    private javax.swing.JTextField numfiche2;
    private javax.swing.JTextField postnom;
    public static javax.swing.JPanel pphysique;
    private javax.swing.JTextField prenom1;
    private javax.swing.JTextField prenom2;
    private javax.swing.JTextField prenom3;
    // End of variables declaration//GEN-END:variables
}
