/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

/**
 *
 * @author BIENFAIT
 */
public class Vaccination extends javax.swing.JPanel {

    /**
     * Creates new form Vaccination
     */
    public Vaccination() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jcheck1 = new javax.swing.JCheckBox();
        jcheck2 = new javax.swing.JCheckBox();
        Jcheck3 = new javax.swing.JCheckBox();
        Jcheck4 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 204)), "Information sur physique", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 14), new java.awt.Color(0, 0, 255))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jcheck1.setBackground(new java.awt.Color(255, 255, 255));
        jcheck1.setText("Pneumo 2");
        jPanel2.add(jcheck1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jcheck2.setBackground(new java.awt.Color(255, 255, 255));
        jcheck2.setText("BCG");
        jPanel2.add(jcheck2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        Jcheck3.setBackground(new java.awt.Color(255, 255, 255));
        Jcheck3.setText("DTC-HepB-Bib 2");
        jPanel2.add(Jcheck3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        Jcheck4.setBackground(new java.awt.Color(255, 255, 255));
        Jcheck4.setText("VPOb 0");
        jPanel2.add(Jcheck4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 0, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("VACCINATION");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 130, 30));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 570));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Jcheck3;
    private javax.swing.JCheckBox Jcheck4;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox jcheck1;
    private javax.swing.JCheckBox jcheck2;
    // End of variables declaration//GEN-END:variables
}
